Repository nirajgiriXD/garden-of-quotes, pull requests merged in 2024-01, with the labels that each got.

#28 Feat: Search feature added.
  package-lock.json
  package.json
  src/components/Search/SearchBox.css
  src/components/Search/SearchBox.tsx
  src/components/navbar/navbar.tsx
  src/components/quoteBox/quoteBox.tsx
Labels: enhancement, work-on-progress

#32 Refactor search
  src/assets/css/search-box.css
  src/assets/css/style.css
  src/components/searchBox/searchBox.tsx
Labels: enhancement

#50 Add new quote
  public/quotes.json
Labels: add new quote
